### ISSUE TITLE
Routing issue

### ISSUE THREAD

**Issue by imxaander** [imxaander/cdm.edu.ph#13]
Since we are just including nav, its links are going to be the same even when it is in other directories,
 resulting into this:

![image](https://github.com/imxaander/cdm.edu.ph/assets/73865197/2e019153-2be0-4ab0-af36-ab9f045d5c2e)

im working on a fix, tell me if you have any suggestions

**Comment by rohb22** [comment]
The easiest solution I found was to include the repository name in the href attribute, like this: <a href="cdm.edu.ph/admission/index.html">Admission</a>. However, this is not an ideal fix and cannot be run locally. I also looked into using the <base href="/cdm.edu.ph/"> tag, but this approach would break file imports such as CSS and scripts.

**Comment by imxaander** [comment]
i think it can be solved by a function that does this :

1. check if the location is root. if location is in root, exit
2. if not in root, update every href inside nav and footer with additional `.` in their href.

ill test this code
```js
    console.log(location.pathname);
```
in gh pages to check if it validates correctly

**Comment by imxaander** [comment]
it displays this, which is the same in local testing
gh page:
![image](https://github.com/imxaander/cdm.edu.ph/assets/73865197/39ee2518-fb8c-4c7b-917f-4d5a1bc2a4a9)

local:
![image](https://github.com/imxaander/cdm.edu.ph/assets/73865197/49186db8-c36c-46a4-a187-aed21964ffee)

ill write the fix for this.

**Comment by imxaander** [comment]
thanks, @rohb22  fixed.
